- name: EPEL
  yum: name=epel-release state=present
  when: ansible_distribution == "CentOS"

- name: Standard packages
  yum: name={{ item }} state=present
  with_items:
    - libselinux-python
    - btrfs-progs
    - man
    - less
    - vim-enhanced
    - yum-plugin-remove-with-leaves
    - ansible
    - git
    - rsync
    - wget
    - net-tools
    - firewalld

- service: name=firewalld enabled=true state=running

- block:
    - selinux: state=disabled

    - name: Host only Packages
      yum: name={{ item }} state=present
      with_items:
        - pciutils
        - gdisk
        - iptraf-ng

    - name: Disable NetworkManager
      service: name=NetworkManager enabled=no
  when: ansible_virtualization_role == 'host'
